#logging:
#  level:
#    #        tk.mybatis: DEBUG
#    com.smart.iot.pay: DEBUG
#server:
#  port: 9993
#
#spring:
#  application:
#    name: smart-pay-server
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null
#  datasource:
#    name: test
#    url: jdbc:mysql://localhost:3306/itparking?useUnicode=true&characterEncoding=UTF8
#    username: root
#    password: smart.IOT@YUNCITYS52
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#  redis:
#    database: 10
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:smart.IOT@YUNCITYS52_redis}
#    pool:
#      max-active: 20
#    topic: __keyevent@0__:expired
#  task:
#    pool:
#      corePoolSize: 10
#      maxPoolSize: 20
#      keepAliveSeconds: 60
#      queueCapacity: 100
#      threadNamePrefix: myThreadPool
#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:localhost}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: admin
#    password: admin@yuncitys.com
#    zipkin:
#      enabled: true
#    sleuth:
#      sampler:
#        percentage: 1
#
## 配置数据库
#mybatis:
#  mapper-locations: "classpath*:mapper/*.xml"
#
## 配置swagger
#swagger:
#  enabled: true
#  base-package: com.smart.iot.pay
#  title: smart-pay-server
#  version: 1.0.0.SNAPSHOT
#  description: 城市智能停车平台
#  contact:
#    name: admin
#  # 鉴权策略ID，对应 SecurityReferences ID
#  authorization:
#    name: Authorization
#    key-name: Authorization
#    auth-regex: ^.*$
## 配置用户认证和服务认证信息
#auth:
#  serviceId: smart-auth
#  user:
#    token-header: Authorization
#    limit-expire: 1440 # 一天过去,单位分钟
#  client:
#    id: smart-pay-server
#    secret: 123456
#    token-header: client-token
#  oauth:
#    clientId: app
#    clientSecret: app
#    grantTypes: password,refresh_token
#    scope: app
#
#mapper:
#  mappers: com.yuncitys.smart.security.common.mapper.CommonMapper
## 跨服务数据合并
## 跨服务数据合并
#merge:
#  enabled: true
#  guavaCacheNumMaxSize: 1000 # 缓存总个数
#  guavaCacheRefreshWriteTime: 10 # 缓存⾃自动刷新时间，单位分钟
#  guavaCacheRefreshThreadPoolSize: 10 # 缓存异步刷新线程数⼤大⼩小
#  aop:
#    enabled: true # 是否开启⾃自动切⾯面数据聚合
#alipay:
#  ali_app_partner: 2088721534104742
#  ali_app_seller_id: YUNCITYS@yuncitys.com.com
#  ali_notify_url:  https://www.parking.yuncitys.com.com/api/parking/pay/alipay_notify.html
#  ali_app_id: 2018082361123405
#  ali_private_sign: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCG8CTx+YPEgc2Y+s+HiWlzs7tu1hMrCZViW4a8h8WbvKHTngDT4JQ1eXMKNKQi74zPCQFVENNpQKlEH3KUs6yWNoSnXPfvcfwN4sgUFwh7wnqII7xfL1o4V9/723ZTU1FznwPjQLUSyKVJ4D1raYTJF56xopwQGzt221IWhV6S4tG+bJv2e9oAdnu7GSrfLWfnB9zVO6tVK7iGgLb1ax9TkwioA4eXWi9Ogd5nhKv4gR57IpqI64IZClfSjqyykLHBnWS7wRkUM0mTMH+s063bWRCUoCZ5qRPu4XAJQaOg/DSbj6ScrmcKNZIN7zcbzH+pxHZ+HtM9slqNoLLDAbWVAgMBAAECggEAOhRC0qPCw2HbTG0nxf6vFM3Xbu1VcsC9O4iJhbwqoc2fGaZ4VLnlEN8lVM8zlpXk1XfayvJjDHp4YInol3h+YGk2z5KEZNt60b86vurrC9m5Q7+d5JpNCtNH5O+hDlxeQpW+5qGDToJuIk4SIZlZPfScqXiEE6qk/ZOI0Yi2HCJEb5k8ewFiNq50hvGmCKTnQtIMDJReTeRTwHgvScZvI3tSgk42LoE/r61dJndLu8DrAc9iv4M8qbmzBJe8x1FfhFhPnLAKYQA3cllxyGQm0c3oNYrWmCCGMY1YcPiDUTPe1E+NsNNtS7c0zlGBe0EBQIrLCmg8BS78R5kf7/UwAQKBgQDAFzkhlQKpc/6kFFTPHgWs9C6Nh76gf5H7udVfkujcMDOn+/RY0THCVa5KJgCOoHoFkjAbU6l8inALUcmFZAJ5AhxcGQi/4ds9CuRLW8U2fvUY8mayknheQk8sHV+E0Dj+tYjEW0PgrzG+4W9GWz/AnoohcirrdSJuaez2hU5VVQKBgQCz1RuN8flJmKjSFaYuysjpMxdSzNTLNpMwMg+JUXe5+QW7Ay1PCjFMukTekTHDJIJ2QNkwhA0OTApIc+TxAgxYNMKho3MFQe4dyexUiTKhRYzTJ8mIft309yz3H0clQvmpsxLo9uotyXoEyNSZE5XtD3mJkH8+7lyBf2yD9qXfQQKBgDQPlzpUym3mtCMAJ6QivOMNIvjUy4NwT75rtTq79ESJA9cJYEYaHGRRGHWcKxZ8w9Vys3sUh6DrXEaVGgr++fSV792+IzLuIZ8/rnQGIUMN0Zu7Rr4rGFhjnFWWeGbkkC3oQXMGUTU6Bj93ldL5tCOeVE2QRbWe/3/xUXnW004pAoGACXjkJqnkM5gy7D3vru9HfeEPDXF0k++f+R3p65W69LTFNICKVmt3BU+aaQ7EzD6UEJ6B0ihid6pRsFdKa9drxwmgZtsxJ8m9PRxxslI3tH7xV/30g5gLIOgUGkAvgyrv85xXFqZK13aRUscxS47YitAR2skdqrbrcHbBxIGtYwECgYAzonjqkvB9eN/wyaSZjJrsfG4EQ+NoEgTWGw5HX3J58uH9SFMgBmHwmHmmMfChWWMU0HtjG4TnptZVGVs/cu+7NVpBrT2i6GwlWO3pV+KQpCS7iIGJQdychMJoJP7L7GTjrHHHqZpj6Y7YBg35lrOJITBC08lbuYuBLpxLR6BAvA==
#  #  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCasU9lVvzXWaOL5HV+6TWYvUT/34Bh5smyXXBOuFtblTHL1TczOkxBaFr6v5+8ujrsM58Eque1MnvU6hdhQaVgIboLtBfVg9QHLGB71a35eJKQttks0hFI0ryWiJAdDl6mxhIbixcCUKUB89Dna0xkfkBjBBlpTAAaODT53QMyHJKihWnqCBjQ+QsC0QKDkSRxge0Z7nR7FwSrHFofd0UQd82t4te81UawoXKa0iqhb35yqc8s6vcvZn2xrZ7tzipFKCojx6DNWsT8gZSNuG1Td8p+GCnV0txb26YES4lHFe6ehpEfEp+Vw3Hpj5NjePGxcIjZMuhLN16b66D/WdX7AgMBAAECggEADqCXhlicXeye91pp9c8tfzzeameC5z8AcXo+ZWMvWFCaPdDygEiR71ljyPQXsavWaIFVFwbmFA8rAG4GOe8QKS/nPLYRzuHBSdBbazpAUiehjEeN75wJgF5U8NMG9YhnUNPH4IzdZx2jDLU2WrudpJ7/jZ1Unc1O8SvBbqMEa1d8cExKXzZMOn++hyfvOKLILzo3O++Ba/vMFaKBwtBXL6/MnJWsxhyKUCyEsRqlD2MRLVxPxlk9ZP0m1fOuBVAGaTgITx5gftFUafGWcadLmKAO7MjavSOGVY8Kk0ZNKvxuYUtzSsKNzPRurgWqu6HIr6dd0uDbCbTNyx9vatti8QKBgQDfLCDGlHRCGoa5vl/RatONseJHJoIWuooW297B+vSPxVVB8Vfkqz521tBF+4+3AatJwjgAV7KXeRBxPBJn+gI25I+kA663wqZbkGijUdXytd4OcX+JkCZjpZHHL4kcr8eywq/66iiA3H8bT0zFg+wV+gzc8aUba+3A6wa0j2xTWQKBgQCxcnrV1gZfv1RTNor0LoLPzDTstY0cS+GSKljCmKvFR4qisG1Qr8tseFTrHpr5DhncL1RjsB95cGqg4hDeGBtHJQIMym7E4yL9bQGWAsNnPo9NOFpZjJe21t3ryhtDrpRyPAQA/DOrp0mO+O4LqT9DrSRn2zcifDtidH02Xt/tcwKBgFnkjncuiP2vbaEXu8TAwOIMStbZ/gBltwWqHroH+caHd+YN7pdfGtQHhvEJeUP/2hzlrGUG7hrxWtwhlFBpdcbinbE1AoVmVFgBfQR8DC+tbfpnYTXp6Gyu3l9bGGGDtG6e2P+6ngH5zwETGhtdHhVkGRZOB3FaMfRJNvQ36SxRAoGAU8n82rA/PkL4LHrazkaQGlMQwp1Pzoa+MuiwFONGaNdJTV0FoU4BPmzrnEJNZ0ETUPdAX/owQoWks+dLk7PKXaPJ/gQwneOrCAPK9ezEHCJcRFhRwWsz0HBRRh+fFCyBiBdyxIxSUcGiaFJ/BR6b8vb08919gVksKWdcIKpYDqUCgYAWRjDflkfwi8tEAEkgTfqWo+C9+KCTkwO8/7JGswkCqWwylKpYo/E0U/IRysEvkZnEcnyx40LZhxaPTx8LM13LScqYOMOu+GHRF6LqmvX8zPu+OXqLIu1EE3ziq9YhQn96oyWKZQETkAFuV+nCMQnybsnA5gWP4LU9ygrFMWbI1Q==
#  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAltE61S1LGAFo/ROpkBpETtM/xtWi8udIDlWvID3kbJv1AgMJj+f0gtNP8RUKxg94qv0dYd72KL1pMox6HJroe23S23+mtgAddItU8YA9fW1p5yJr5XpeUjPIzKoVBynFtNywTb7XlWP3zrYOQdiaEUsotbXSx5FNGraPCAR6HGVCA4lHuQa8Y22/Q0Pu9TKl7Ko8ERaRm7q/Sd9+Ivg/6hIPMD25yj7U+3ohiXS9fvp+12IEqCT8rG3WyDBVAVhGB8ALNFniMcyIjiMS+5ZEj9NPCA3si4T5FKqcH+x8tQG/qRCH2gaO/SwK3VVwYo9Itg7QGP/UDYGBr4aOJuECcQIDAQAB
#  #  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmrFPZVb811mji+R1fuk1mL1E/9+AYebJsl1wTrhbW5Uxy9U3MzpMQWha+r+fvLo67DOfBKrntTJ71OoXYUGlYCG6C7QX1YPUByxge9Wt+XiSkLbZLNIRSNK8loiQHQ5epsYSG4sXAlClAfPQ52tMZH5AYwQZaUwAGjg0+d0DMhySooVp6ggY0PkLAtECg5EkcYHtGe50excEqxxaH3dFEHfNreLXvNVGsKFymtIqoW9+cqnPLOr3L2Z9sa2e7c4qRSgqI8egzVrE/IGUjbhtU3fKfhgp1dLcW9umBEuJRxXunoaRHxKflcNx6Y+TY3jxsXCI2TLoSzdem+ug/1nV+wIDAQAB
#  alipay_public_keys: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlT1fu6kjwlSaww4Avfg1Uz4boKojVNMENc6RmM0mfUJznPgASjC4eHDMA7oADMq5Mf32l4OedkyvlzyVg+kDILbcMQhNiE6o4h2YEF4jtJ0WBvCS2w5AZPHvAs59R8JkuPa5ZGuCVdYh6Gt4c5dIF+sT80NtN2WUiWE5ZqffS1c/ztvcn5uN5onmEbjbMwpW+QuMh1jBHDccNI3BZJjyVMrD0Gyo0TRrSObCTB0yKYAqZJmnuBpOlVT15QBV/gzx+o7K3+gyDaR9yhkwQC5QOEDiBxneC1QrwT+oWgjnj8pYGBq9QReBu14HlCaqH0FKzn2+XpcbjYzhul1YuLtJqwIDAQAB
#wcpay:
#  wc_app_appid: wx8c1c3b7654729679
#  wc_app_mchid: 1514119501
#  wc_app_apikey: YUNCITYSingiioweofl66255uowenfnosdj4
#  wc_app_notify_url: https://www.parking.yuncitys.com.com/api/parking/pay/wechat_notify.html
#  wc_cert_path: /usr/local/application/apiclient_cert.p12
#
#  wc_pda_appid: wx987ca8e374095ac5
#  wc_pda_mchid: 1483515042
#  wc_pda_secret: 640264512eef7ab4df81a2094c4d01d6
#  wc_pda_apikey: YUNCITYSingiioweofl66255uowenfnosdj4
#  wc_pda_notify_url:  https://www.parking.yuncitys.com.com/api/parking/pay/pda_weixin_notify.html
#  wc_pda_program_id: wx5780c6fe0d70b129
#ssl_enabled: N
#sysPath: parking.oss-cn-shenzhen.aliyuncs.com
#unionpay:
#  unionpay_url: http://szwgzftest.unionpay.com/access/unionpayPark
#
#rpc:
#  api_url: http://localhost:8080
#  rpc_url: /api/plugins/rpc/twoway/
#  get_devparams_url: http://localhost:8080/api/customer/88ba19f0-6eaf-11e8-a1e4-d1b282189b3a/devices
#  get_token_url: /api/auth/login
#  username: caoyingde@yuncitys.com.com
#  password: sysadmin
#  qr_code_url:
##MQTT配置信息
#mqtt:
#  #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
#  host: tcp://localhost:1884
#  clientinid: subClient_${random.value}
#  clientoutid: ${random.value}
#  #MQTT-默认的消息推送主题，实际可在调用接口时指定  iot/experTopic/#
#  topic: iot-topic/gw/#
#  #发布到APP的topic
#  appTopic: iot-topic/app/
#  webTopic: iot-topic/web/
#  pdaTopic: iot-topic/pda/
#  qoslevel: 1
#  #MQTT-用户名
#  username: adminYUNCITYS
#  #MQTT-密码
#  password: admin123456
#  #10S
#  timeout: 10000
#  #20s
#  keepalive: 20
#baiduMap:
#  routematrixUrl: http://api.map.baidu.com/routematrix/v2/driving
#  ak: xkhItKCfERm5yRScsfPuDGnWbWzOS2Po
#
#eureka:
#  instance:
#    statusPageUrlPath: /info
#    healthCheckUrlPath: /health
#    #docker 部署开启,记得将IP修改为部署所在服务器的外网IP
#    prefer-ip-address: true
#    ip-address: localhost
#  client:
#    serviceUrl:
#      # defaultZone: http://localhost:8761/eureka/
#      # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
#
##请求和响应GZIP压缩支持
#feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
#
#ribbon:
#  eureka:
#    enabled: true
#  ReadTimeout: 220000
#  ConnectTimeout: 220000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 0
#  OkToRetryOnAllOperations: false
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 5000
#      maxQueueSize: 5000
#      queueSizeRejectionThreshold: 1000
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 100000
#          strategy: SEMAPHORE
